baseurl = "https://triades.org/"
languageCode = "en-us"
title = "Triades"
theme = "agency"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) or
    # most longer texts.
    #
    # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Shani Herrmann"
    description = "Triades Group Coaching"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "shani@triades.org"


    # Navigation
    [params.navigation]
		brand = "Triades"
        services = "Triades"
		about = "Why"
        portfolio = "How"
        team = "About"
        contact = "Contact"


    # Hero section
    [params.hero]
        # To change the background image of the hero, replace 'header-bg.jpg' in
        # the 'static/img' folder.
        title = "Triades"
        subtitle = "Group Coaching in 3's"
        buttonText = "Delete me and put Fast Forward icon"


    # Services section
    [params.services]
        title = "A 3-Month Coaching Program to Structure & Support Your Goals"
        subtitle = ''' Fast Forward By the Power of 3
Support: 	3 people to believe in you, a lot and often.
			Accountability to your Triade
Structure: 	8 productive sessions featuring structured exercises, 
           	An online platform to keep your Triade updated regularly on your progress forums
		   	An Action Plan and Deadlines to keep you moving
Fresh Perspectives: new ideas from people outside your entourage, filtered 
'''
    # Testimonials
    [params.testimonials]
        title = "In Their Own Words"
        subtitle = "Testimonials from Former Participants"
        [[params.testimonials.list]]
            avatar = "/img/testimonials/Emmanuelle.jpeg"
            name = "Emmanuelle"
            jobtitle = "Entrepreneur"
            quote = "Triades helped me find new avenues for my business and talents I didn’t know I had.  A great tool for both professional and personal development."

        [[params.testimonials.list]]
            avatar = "/img/testimonials/Sebastien Hert.jpg"
            name = "Sébastien"
            jobtitle = "Supply Chain Manager"
            quote = "Triades transforms the skills and potential of each member into resources that help each person achieve their goal, step by step, together.  It's your base camp before you reach the summit."


    # Program
    [params.program]
    title = "10 hours of coaching for 399€"
    subtitle = "Satisfied or Your Money Back"
        [[params.program.sessions]]
            sessionNumber = 1
            title = "Brainstorming"
            description = "Focus Your Efforts"
            weekNumber = "Week 1"
            duration = "2h"
        [[params.program.sessions]]
            sessionNumber = 2
            title = "Action Planning"
            description = "Get Concrete"
            weekNumber = "Week 2"
            duration = "2h"
        [[params.program.sessions]]
            sessionNumber = 34567
            title = "Coaching"
            description = "Advance Together"
            weekNumber = "Weeks 4, 6, 8, 10"
            duration = "1h x 4"
        [[params.program.sessions]]
            sessionNumber = 8
            title = "Look Ahead"
            description = "Inventory & Next Steps"
            weekNumber = "Week 12"
            duration = "2h"
    
    # Call section
    [params.call]
        title = "A Small, Concrete Action"
		description = '''
Schedule a 15-minute call with Shani to see if Triades is right for you.
'''
    # FAQ section
    [params.faq]
        #description = ""

        [[params.faq.questions]]
            q = "Who is in my Triade?"
            a = '''
People who are professionally very different from you. This diversity is one of the great strengths of Triades. A concrete example explains why:

If your goal is to start a community recycling program, who would you want in your Triade: someone who recycles or someone who doesn’t? A social action veteran or a social media manager? 

People who are different from you can help you uncover your assumptions and see new possibilities because they move in different circles and think in different ways. Still, similarities pop up where you least expect them. The social media manager’s wife who’s a social action veteran. The non-recycler’s husband who works at the local newspaper. 

Triades is based on reciprocity: you help others with their goals and they help you. You might become close with somebody who opens crucial doors for you. Or who, at the very least, helps you see possibilities you didn’t know you had. Times 3. 
'''
        [[params.faq.questions]]
            q = "Who is my coach?"
            a = '''
Shani Herrmann is the creator of Triades. She has a long track record of showing people they can do it! - whatever ‘it’ is. More information in the [About](#about) section.
'''

        [[params.faq.questions]]
            q = "What if Triades doesn’t work for me, or I don’t like it, or...?"
            a = '''
Easy: you get your money back at the end of the 3-month commitment, no questions asked, if you are not satisfied for any reason.

We do ask that you attend all sessions until the end, if not for yourself, for your fellow Triade members. They count on your ideas and contributions.  A Triade with only 2 people is not a Triade!

Our money-back guarantee means that you can fully commit to the process and your goal.  What would you do if you knew you could not fail?
'''
    
    # Portfolio section
    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Testimonials"
        subtitle = "From past clients, in their own words." 

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
    [params.about]
        title = "Why Shani?"
        subtitle = ""
        endpoint = "Your<br>Project"

        # The events will be listed from the top to the bottom.
        # All images are stored under 'static/img/about'.
        # Replace them with your own.
        [[params.about.events]]
            img = "right brain left brain.jpg"
            date = ""
            title = "Analysis & Intuition"
            description = "Right brain or left brain? Shani is both. Sensitive to nuances in design, language, and emotion. Logical and results-oriented. You get the best of both worlds."

        [[params.about.events]]
            img = "globe 200.jpg"
            date = ""
            title = "Extensive Cultural Experience"
            description = "Shani has lived in North and South America, Europe and the Middle East, has travelled extensively and has worked with people from many different disciplines all over the world. She'll figure out your brand's culture - and the culture of the context you operate in - in no time."

        [[params.about.events]]
            img = "montessori cube 200.jpg"
            date = ""
            title = "A Co-Creative Approach"
            description = "Shani's approach to working with clients has its roots in Montessori - Shani's family business. It's about working together to find solutions in a positive, relaxed environment where creativity flows."

    # Team section
    [params.team]
        title = "About"
        subtitle = ""
        description = "Both analytical and empathetic, Shani has many years’ experience as a teacher, trainer and coach leading groups and creating learning through structured activity. Her joy in life is when others find greatness in themselves. Helping them find it is her greatness. She leads Triades in English, French, Spanish and Portuguese."
       # All team member's pictures are stored under 'static/img/team'.
        # Replace them with your own too.

        [[params.team.members]]
            img = "shani-portrait.jpg"
            name = "Shani Herrmann"
            position = "Creator of Triades"
            social = [
                ["fa-twitter", "#"],
                ["fa-facebook", "#"],
                ["fa-linkedin", "https://fr.linkedin.com/in/shaniherrmann"]
            ]

    # Client section
    # All the clients' logos are stored under 'static/img/logos'.
    # Replace them with your clients's logos.
    [[params.clients]]
        logo = ".jpg"
        link = "#"

    # Contact section
    [params.contact]
        title = "Let's Talk"
        subtitle =  "Give Shani a call at [+33 6 41 88 23 40](tel:+33641882340) or write her a note here.<br></br> She'll get back to you within 1 business day."
        buttonText = "Send"

        # 'warning' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Your Name *"
            warning = "Please enter your name."

        [params.contact.form.email]
            text = "Your Email *"
            warning = "Please enter your email address."

        [params.contact.form.phone]
            text = "Your Phone *"
            warning = "Please enter your phone number."

        [params.contact.form.message]
            text = "Your Message *"
            warning = "Please enter a message."


    # Footer section
    [params.footer]
        copyright = "Published under the Apache License 2.0."

        [[params.footer.social]]
            icon = "fa-twitter"
            link = "#"

        [[params.footer.social]]
            icon = "fa-facebook"
            link = "#"

        [[params.footer.social]]
            icon = "fa-linkedin"
            link = "https://fr.linkedin.com/in/shaniherrmann"

        [[params.footer.quicklinks]]
            text = "Privacy Policy"
            link = "#"

        [[params.footer.quicklinks]]
            text = "Terms of Use"
            link = "#"

